#!/usr/bin/env python3
"""Egla-Kafe resolution ablation — paired 4-arm comparison (Workstream R, July 2026).

Compares the same 175 iPhone-4K turn segments (5 videos, identical segments.json — sha256-verified)
decoded at four input resolutions:

  baseline    original June-24 run, native 4K hand-crops (10-bit, 1200/1300 px)
  res4k_ctrl  scale x1.0 re-encode (controls the extra encode generation + 10->8-bit)
  res2k       scale x2/3  (800/866 px crops ~ "2K capture")
  res1080     scale x0.5  (600/650 px crops ~ "1080p capture")

Primary metrics are computed on the hyp_mbr displayed text (production default since May 2026);
top-1 is reported as secondary for continuity with the June baseline numbers. If a
`report_mbr/report.csv` is missing for an arm, it is regenerated by running
VSP-LLM/scripts/make_report.py --display-method hyp_mbr --aggregated <archive aggregated.json>
on that arm's hypo-corrected.json (same scoring machinery as the shipped top-1 reports).

Outputs:
  docs/evaluation/egla_kafe/plots/resolution_metrics_by_condition.png
  docs/evaluation/egla_kafe/plots/resolution_mouthpx_vs_delta.png
  docs/evaluation/egla_kafe/resolution_ablation_stats.json
  full text summary on stdout (numbers for resolution_ablation.md)

Caveat handled explicitly: per-segment references come from the decode-anchored monotonic script
aligner (align_script_to_segments.py), so refs can shift between arms on the same utt_id
(quantified below). Arm-level means are robust to this (the aligner redistributes the same script
lines within a video); per-segment paired tests are additionally checked against a FIXED reference
set (the June baseline alignment) via a WER sensitivity re-computation.

stdlib csv/json + numpy/scipy + matplotlib (Agg). Venv: /home/ubuntu/vsp-llm-yoad-venv.
"""
import csv
import json
import math
import os
import re
import subprocess
import sys

import numpy as np
from scipy import stats as sps

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = "/home/ubuntu"
RES_ROOT = f"{ROOT}/datasets/clients/egla_kafe_resolution"
BASE_EVAL = f"{ROOT}/datasets/clients/egla_kafe/work/eval"
PLOTS_DIR = f"{ROOT}/docs/evaluation/egla_kafe/plots"
STATS_JSON = f"{ROOT}/docs/evaluation/egla_kafe/resolution_ablation_stats.json"
LIP_TXT = f"{BASE_EVAL}/lip_pixel_measurements.txt"
MAKE_REPORT = f"{ROOT}/VSP-LLM/scripts/make_report.py"

ARMS = {  # ordered: native -> most downscaled
    "baseline": {
        "label": "4K baseline (June)",
        "report": f"{BASE_EVAL}/run_shaam_all/report/report.csv",
        "report_mbr": f"{BASE_EVAL}/run_shaam_all/report_mbr/report.csv",
        "hypo_corrected": f"{BASE_EVAL}/run_shaam_all/hypo-corrected.json",
        "aggregated": f"{ROOT}/flat_runs_archive/20260624_200135/client_outputs/report/aggregated.json",
        "provenance": f"{BASE_EVAL}/run_shaam_all/provenance.json",
        "lip_section": "iPhone-4K decode inputs (img_*)",
    },
    "res4k_ctrl": {
        "label": "res4k_ctrl (x1.0 re-encode)",
        "report": f"{RES_ROOT}/res4k_ctrl/work/eval/run_all/report/report.csv",
        "report_mbr": f"{RES_ROOT}/res4k_ctrl/work/eval/run_all/report_mbr/report.csv",
        "hypo_corrected": f"{RES_ROOT}/res4k_ctrl/work/eval/run_all/hypo-corrected.json",
        "aggregated": f"{ROOT}/flat_runs_archive/20260716_185819/client_outputs/report/aggregated.json",
        "provenance": f"{RES_ROOT}/res4k_ctrl/work/eval/run_all/provenance.json",
        "lip_section": "ABLATION res4k_ctrl crops",
    },
    "res2k": {
        "label": "res2k (x2/3)",
        "report": f"{RES_ROOT}/res2k/work/eval/run_all/report/report.csv",
        "report_mbr": f"{RES_ROOT}/res2k/work/eval/run_all/report_mbr/report.csv",
        "hypo_corrected": f"{RES_ROOT}/res2k/work/eval/run_all/hypo-corrected.json",
        "aggregated": f"{ROOT}/flat_runs_archive/20260716_202731/client_outputs/report/aggregated.json",
        "provenance": f"{RES_ROOT}/res2k/work/eval/run_all/provenance.json",
        "lip_section": "ABLATION res2k crops",
    },
    "res1080": {
        "label": "res1080 (x0.5)",
        "report": f"{RES_ROOT}/res1080/work/eval/run_all/report/report.csv",
        "report_mbr": f"{RES_ROOT}/res1080/work/eval/run_all/report_mbr/report.csv",
        "hypo_corrected": f"{RES_ROOT}/res1080/work/eval/run_all/hypo-corrected.json",
        "aggregated": f"{ROOT}/flat_runs_archive/20260716_213309/client_outputs/report/aggregated.json",
        "provenance": f"{RES_ROOT}/res1080/work/eval/run_all/provenance.json",
        "lip_section": "ABLATION res1080 crops",
    },
}
ARM_ORDER = ["baseline", "res4k_ctrl", "res2k", "res1080"]
PAIRS = [("baseline", "res4k_ctrl"), ("res4k_ctrl", "res2k"),
         ("res4k_ctrl", "res1080"), ("res2k", "res1080")]
STEMS = ["img_6821", "img_6822", "img_6823", "img_6824", "img_6825"]

# Context-aware per-video Y+P (July per_video_understanding.md, judged on the June top-1 texts)
CONTEXT_YP = {"img_6825": 72.7, "img_6824": 66.7, "img_6822": 35.3,
              "img_6821": 19.0, "img_6823": 14.8}

TOKEN_RE = re.compile(r"[a-z0-9]+(?:'[a-z0-9]+)?")
STEM_RE = re.compile(r"^(img_\d+)_")

# --- dataviz reference palette (light mode), fixed slot per video -------------------------------
VIDEO_COLORS = {"img_6821": "#2a78d6", "img_6822": "#008300", "img_6823": "#e87ba4",
                "img_6824": "#eda100", "img_6825": "#1baf7a"}
INK, INK2, MUTED, GRID, BASELINE_AX, SURFACE = ("#0b0b0b", "#52514e", "#898781",
                                                "#e1e0d9", "#c3c2b7", "#fcfcfb")


def toks(s):
    return TOKEN_RE.findall((s or "").strip().lower())


def fnum(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return None


def ci95(vals):
    vals = [v for v in vals if v is not None and not (isinstance(v, float) and math.isnan(v))]
    if not vals:
        return (None, None, None, 0)
    a = np.array(vals, dtype=float)
    m = float(a.mean())
    if len(a) < 2:
        return (m, m, m, len(a))
    se = a.std(ddof=1) / math.sqrt(len(a))
    t = sps.t.ppf(0.975, len(a) - 1)
    return (m, m - t * se, m + t * se, len(a))


def ensure_mbr_report(arm):
    c = ARMS[arm]
    if os.path.exists(c["report_mbr"]):
        return
    out_dir = os.path.dirname(c["report_mbr"])
    print(f"[regen] {arm}: building MBR-displayed report -> {out_dir}", file=sys.stderr)
    subprocess.run([sys.executable, MAKE_REPORT, "--jsonl", c["hypo_corrected"],
                    "--out_dir", out_dir, "--compute-is",
                    "--aggregated", c["aggregated"], "--display-method", "hyp_mbr"],
                   check=True)


def load_report(path):
    """report.csv -> {utt_id: row-dict with parsed metrics} (img_* rows only)."""
    out = {}
    with open(path, encoding="utf-8") as f:
        for r in csv.DictReader(f):
            u = r["utt_id"]
            if not u.startswith("img_"):
                continue
            out[u] = {"ref": r["ref"], "hyp": r["hyp"],
                      "wer": fnum(r["wer_%"]), "wwer": fnum(r["wwer_%"]),
                      "nea_f1": fnum(r["nea_f1_%"]), "is": fnum(r["is_score"])}
    return out


def load_word_probs(arm):
    """Per-segment mean raw word prob from aggregated.json: hyp_mbr.word_confs + hyp_top1_word_confs."""
    agg = json.load(open(ARMS[arm]["aggregated"], encoding="utf-8"))
    mbr, top1 = {}, {}
    for u, v in agg.items():
        if not u.startswith("img_"):
            continue
        wc = (v.get("hyp_mbr") or {}).get("word_confs") or []
        ps = [p for _, p in wc if isinstance(p, (int, float))]
        mbr[u] = float(np.mean(ps)) if ps else None
        wt = v.get("hyp_top1_word_confs") or []
        pt = [p for _, p in wt if isinstance(p, (int, float))]
        top1[u] = float(np.mean(pt)) if pt else None
    return mbr, top1


def load_align_conf(arm):
    prov = json.load(open(ARMS[arm]["provenance"], encoding="utf-8"))
    return {u: p.get("align_conf") for u, p in prov.items() if u.startswith("img_")}


def parse_lip_px():
    """lip_pixel_measurements.txt -> {arm: {stem: {frame,face,mouth}}} (medians, FaceMesh)."""
    sec_to_arm = {c["lip_section"]: a for a, c in ARMS.items()}
    out = {a: {} for a in ARMS}
    cur = None
    row_re = re.compile(r"^\s+(img_\d+): frame (\d+)x\d+, face~(\d+)px, MOUTH~(\d+)px")
    for line in open(LIP_TXT, encoding="utf-8"):
        m = re.match(r"^== (.+) ==\s*$", line)
        if m:
            cur = sec_to_arm.get(m.group(1))
            continue
        m = row_re.match(line)
        if m and cur:
            out[cur][m.group(1)] = {"frame": int(m.group(2)), "face": int(m.group(3)),
                                    "mouth": int(m.group(4))}
    for a in ARMS:
        assert set(out[a]) == set(STEMS), f"lip px parse incomplete for {a}: {sorted(out[a])}"
    return out


def wer_fixed_ref(ref_text, hyp_text):
    """Uncapped word-level WER (%) with the aligner's tokenization; None if ref empty."""
    import editdistance
    r, h = toks(ref_text), toks(hyp_text)
    if not r:
        return None
    return 100.0 * editdistance.eval(r, h) / len(r)


def arm_summary(rows, word_probs, align_conf):
    """Means over scored rows (ref non-empty -> metric present), matching the June reporting
    basis. n_total=175 everywhere; n_scored varies per arm because the decode-anchored aligner
    matches fewer turns when the decode degrades (itself an outcome, reported)."""
    iss = [r["is"] for r in rows.values() if r["is"] is not None]
    wers = [r["wer"] for r in rows.values() if r["wer"] is not None]
    m_is, lo_is, hi_is, n_sc = ci95(iss)
    m_wer, lo_wer, hi_wer, _ = ci95(wers)
    n = len(rows)
    nonempty = [u for u, r in rows.items() if r["hyp"].strip()]
    return {
        "n_total": n, "n_scored": n_sc,
        "is_mean": m_is, "is_ci": [lo_is, hi_is],
        "wer_mean": m_wer, "wer_ci": [lo_wer, hi_wer],
        "wwer_mean": ci95([r["wwer"] for r in rows.values()])[0],
        "nea_f1_mean": ci95([r["nea_f1"] for r in rows.values()])[0],
        "useful_pct": 100.0 * sum(1 for v in iss if v >= 2.0) / n_sc,
        "clear_pct": 100.0 * sum(1 for v in iss if v >= 3.0) / n_sc,
        "niv_y_pct": 100.0 * sum(1 for v in iss if v >= 3.80) / n_sc,
        "halluc_pct": 100.0 * sum(1 for v in wers if v >= 100.0) / len(wers),
        "empty_pct": 100.0 * (n - len(nonempty)) / n,
        "mean_word_prob": ci95([word_probs.get(u) for u in rows])[0],
        "mean_align_conf": ci95([align_conf.get(u) for u in rows])[0],
    }


def paired_tests(rows_a, rows_b, key):
    """Wilcoxon signed-rank on per-segment metric `key` for arms a->b (delta = b - a).
    Pairs where either arm lacks the metric (empty aligned ref) are dropped."""
    common = sorted(u for u in set(rows_a) & set(rows_b)
                    if rows_a[u][key] is not None and rows_b[u][key] is not None)
    a = np.array([rows_a[u][key] for u in common], dtype=float)
    b = np.array([rows_b[u][key] for u in common], dtype=float)
    d = b - a
    nz = int(np.sum(d != 0))
    res = {"n": len(common), "n_changed": nz,
           "mean_delta": float(d.mean()), "median_delta": float(np.median(d))}
    if nz == 0:
        res.update({"W": None, "p": None})
        return res
    try:
        W, p = sps.wilcoxon(a, b, zero_method="wilcox", alternative="two-sided")
        res.update({"W": float(W), "p": float(p)})
    except ValueError as e:
        res.update({"W": None, "p": None, "err": str(e)})
    return res


def text_changed(rows_a, rows_b):
    common = sorted(set(rows_a) & set(rows_b))
    ch = sum(1 for u in common if rows_a[u]["hyp"].strip() != rows_b[u]["hyp"].strip())
    return 100.0 * ch / len(common)


def ref_changed(rows_a, rows_b):
    common = sorted(set(rows_a) & set(rows_b))
    ch = sum(1 for u in common if rows_a[u]["ref"].strip() != rows_b[u]["ref"].strip())
    return 100.0 * ch / len(common)


def fmt_p(p):
    if p is None:
        return "n/a"
    return f"{p:.4f}" if p >= 1e-4 else f"{p:.1e}"


# ------------------------------------------------------------------ plots
def plot_metrics_by_condition(data, lip, out_png):
    """Two panels (IS, WER): per-video lines over the 4 ordered arms + black arm-mean w/ 95% CI."""
    xlabels = ["4K\n(baseline)", "4K ctrl\n(re-encode)", "2K\n(x2/3)", "1080p\n(x0.5)"]
    x = np.arange(4)
    fig, axes = plt.subplots(1, 2, figsize=(11.5, 4.6), dpi=160)
    fig.patch.set_facecolor(SURFACE)
    for ax, key, title, ylab in [
            (axes[0], "is", "Intelligibility Score by input resolution", "mean IS (0–5)"),
            (axes[1], "wer", "WER by input resolution", "mean WER % (uncapped)")]:
        ax.set_facecolor(SURFACE)
        ends = []
        for stem in STEMS:
            ys = [data["per_video"][a][stem][key + "_mean"] for a in ARM_ORDER]
            ax.plot(x, ys, color=VIDEO_COLORS[stem], lw=1.6, marker="o", ms=4.5,
                    alpha=0.9, zorder=2)
            ends.append((stem, ys[-1]))
        # direct end labels with simple collision stagger (min gap = 4% of y-span)
        yspan = (max(e[1] for e in ends) - min(e[1] for e in ends)) or 1.0
        min_gap = 0.055 * max(yspan, 1e-9)
        placed = []
        for stem, y0 in sorted(ends, key=lambda e: e[1]):
            y = y0
            if placed and y - placed[-1] < min_gap:
                y = placed[-1] + min_gap
            placed.append(y)
            ax.annotate(stem.replace("img_", ""), (x[-1], y), xytext=(7, 0),
                        textcoords="offset points", fontsize=8,
                        color=VIDEO_COLORS[stem], va="center")
        means = [data["arms_mbr"][a][key + "_mean"] for a in ARM_ORDER]
        los = [data["arms_mbr"][a][key + "_ci"][0] for a in ARM_ORDER]
        his = [data["arms_mbr"][a][key + "_ci"][1] for a in ARM_ORDER]
        ax.errorbar(x, means, yerr=[np.array(means) - np.array(los),
                                    np.array(his) - np.array(means)],
                    color=INK, lw=2.4, marker="o", ms=6, capsize=3, zorder=3)
        ax.set_xticks(x)
        ax.set_xticklabels(xlabels, fontsize=8.5, color=INK2)
        ax.set_title(title, fontsize=11, color=INK, pad=10)
        ax.set_ylabel(ylab, fontsize=9, color=INK2)
        ax.grid(axis="y", color=GRID, lw=0.7)
        ax.tick_params(colors=MUTED, labelsize=8.5)
        for s in ("top", "right"):
            ax.spines[s].set_visible(False)
        for s in ("left", "bottom"):
            ax.spines[s].set_color(BASELINE_AX)
        ax.set_xlim(-0.25, 3.65)
    handles = [plt.Line2D([], [], color=VIDEO_COLORS[s], lw=1.6, marker="o", ms=4.5,
                          label=s) for s in STEMS]
    handles.append(plt.Line2D([], [], color=INK, lw=2.4, marker="o", ms=6,
                              label="mean over scored segments ± 95% CI"))
    fig.legend(handles=handles, loc="lower center", ncol=6, fontsize=8, frameon=False,
               bbox_to_anchor=(0.5, -0.03))
    fig.suptitle("Egla-Kafe resolution ablation — same 175 segments, hyp_mbr text "
                 "(5 iPhone videos; turn boundaries held fixed)",
                 fontsize=9.5, color=INK2, y=1.005)
    fig.tight_layout(rect=(0, 0.05, 1, 1))
    fig.savefig(out_png, bbox_inches="tight", facecolor=SURFACE)
    plt.close(fig)


def plot_mouthpx_vs_is(data, lip, out_png):
    """Per-video trajectories: measured mouth width (px) vs mean IS across the 4 arms."""
    arm_marker = {"baseline": "o", "res4k_ctrl": "s", "res2k": "D", "res1080": "v"}
    fig, ax = plt.subplots(figsize=(8.6, 5.2), dpi=160)
    fig.patch.set_facecolor(SURFACE)
    ax.set_facecolor(SURFACE)
    ax.axvline(96, color=MUTED, lw=1.2, ls="--", zorder=1)
    ax.annotate("96 px = mouth-crop width\n(96×96 ROI → 88×88 input)",
                xy=(96, 0.985), xycoords=("data", "axes fraction"),
                xytext=(6, 0), textcoords="offset points",
                fontsize=8.5, color=MUTED, va="top")
    ax.axvline(45, color=MUTED, lw=1.2, ls=":", zorder=1)
    ax.annotate("45 px = canonical mouth width\nafter the affine warp (1:1 sampling)",
                xy=(45, 0.30), xycoords=("data", "axes fraction"),
                xytext=(6, 0), textcoords="offset points",
                fontsize=8.5, color=MUTED, va="bottom")
    for stem in STEMS:
        xs = [lip[a][stem]["mouth"] for a in ARM_ORDER]
        ys = [data["per_video"][a][stem]["is_mean"] for a in ARM_ORDER]
        ax.plot(xs, ys, color=VIDEO_COLORS[stem], lw=1.4, alpha=0.75, zorder=2)
        for a, xx, yy in zip(ARM_ORDER, xs, ys):
            ax.plot(xx, yy, marker=arm_marker[a], ms=6.5, color=VIDEO_COLORS[stem],
                    mec=SURFACE, mew=0.8, zorder=3)
        imax = int(np.argmax(xs))
        ax.annotate(stem, (xs[imax], ys[imax]), xytext=(7, 3), textcoords="offset points",
                    fontsize=8.5, color=VIDEO_COLORS[stem])
    mk = [plt.Line2D([], [], color=INK2, marker=arm_marker[a], ls="", ms=6.5,
                     label=ARMS[a]["label"]) for a in ARM_ORDER]
    ax.legend(handles=mk, fontsize=8, frameon=False, loc="upper left", title="condition",
              title_fontsize=8)
    ax.set_xlabel("measured mouth width, median px (FaceMesh mouth corners)", fontsize=9.5,
                  color=INK2)
    ax.set_ylabel("mean IS per video (hyp_mbr)", fontsize=9.5, color=INK2)
    ax.set_title("Per-video IS stays flat as downscaling shrinks mouths 2–3.5×",
                 fontsize=11.5, color=INK, pad=10)
    ax.grid(color=GRID, lw=0.7)
    ax.tick_params(colors=MUTED, labelsize=8.5)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    for s in ("left", "bottom"):
        ax.spines[s].set_color(BASELINE_AX)
    fig.tight_layout()
    fig.savefig(out_png, bbox_inches="tight", facecolor=SURFACE)
    plt.close(fig)


# ------------------------------------------------------------------ main
def main():
    os.makedirs(PLOTS_DIR, exist_ok=True)
    for a in ARM_ORDER:
        ensure_mbr_report(a)

    lip = parse_lip_px()
    reports = {"top1": {}, "mbr": {}}
    wprobs_mbr, wprobs_top1, aligns = {}, {}, {}
    for a in ARM_ORDER:
        reports["top1"][a] = load_report(ARMS[a]["report"])
        reports["mbr"][a] = load_report(ARMS[a]["report_mbr"])
        wprobs_mbr[a], wprobs_top1[a] = load_word_probs(a)
        aligns[a] = load_align_conf(a)
        assert len(reports["top1"][a]) == 175 and len(reports["mbr"][a]) == 175, \
            f"{a}: expected 175 img_* rows"

    # seg-id parity
    ids0 = set(reports["mbr"]["baseline"])
    for a in ARM_ORDER[1:]:
        assert set(reports["mbr"][a]) == ids0, f"utt_id mismatch in {a}"

    data = {"n_segments": 175, "arms_mbr": {}, "arms_top1": {}, "pairs": {},
            "per_video": {}, "lip_px": lip, "correlations": {}, "ref_shift": {},
            "fixed_ref_wer": {}}

    for a in ARM_ORDER:
        data["arms_mbr"][a] = arm_summary(reports["mbr"][a], wprobs_mbr[a], aligns[a])
        data["arms_top1"][a] = arm_summary(reports["top1"][a], wprobs_top1[a], aligns[a])

    # pairwise paired stats (primary: MBR display)
    for pa, pb in PAIRS:
        key = f"{pa}->{pb}"
        rec = {}
        for basis in ("mbr", "top1"):
            ra, rb = reports[basis][pa], reports[basis][pb]
            rec[basis] = {
                "wilcoxon_is": paired_tests(ra, rb, "is"),
                "wilcoxon_wer": paired_tests(ra, rb, "wer"),
                "text_changed_pct": text_changed(ra, rb),
            }
        rec["ref_changed_pct"] = ref_changed(reports["mbr"][pa], reports["mbr"][pb])
        data["pairs"][key] = rec

    # fixed-ref WER sensitivity (all arms' MBR text vs the June baseline alignment refs)
    base_refs = {u: r["ref"] for u, r in reports["top1"]["baseline"].items()}
    fixed = {}
    for a in ARM_ORDER:
        vals = {}
        for u, r in reports["mbr"][a].items():
            w = wer_fixed_ref(base_refs[u], r["hyp"])
            if w is not None:
                vals[u] = w
        fixed[a] = vals
    data["fixed_ref_wer"]["n_scoreable"] = len(fixed["baseline"])
    data["fixed_ref_wer"]["arm_means"] = {a: ci95(list(fixed[a].values()))[0] for a in ARM_ORDER}
    for pa, pb in PAIRS:
        common = sorted(set(fixed[pa]) & set(fixed[pb]))
        aa = np.array([fixed[pa][u] for u in common])
        bb = np.array([fixed[pb][u] for u in common])
        d = bb - aa
        nz = int(np.sum(d != 0))
        rec = {"n": len(common), "n_changed": nz, "mean_delta": float(d.mean()),
               "median_delta": float(np.median(d))}
        if nz:
            W, p = sps.wilcoxon(aa, bb, zero_method="wilcox", alternative="two-sided")
            rec.update({"W": float(W), "p": float(p)})
        else:
            rec.update({"W": None, "p": None})
        data["fixed_ref_wer"][f"{pa}->{pb}"] = rec

    # per-video breakdown (MBR)
    for a in ARM_ORDER:
        data["per_video"][a] = {}
        for stem in STEMS:
            rows = {u: r for u, r in reports["mbr"][a].items() if STEM_RE.match(u).group(1) == stem}
            iss = [r["is"] for r in rows.values() if r["is"] is not None]
            wers = [r["wer"] for r in rows.values() if r["wer"] is not None]
            ctrl_rows = {u: r for u, r in reports["mbr"]["res4k_ctrl"].items()
                         if STEM_RE.match(u).group(1) == stem}
            data["per_video"][a][stem] = {
                "n_total": len(rows), "n_scored": len(iss),
                "is_mean": ci95(iss)[0],
                "wer_mean": ci95(wers)[0],
                "useful_pct": 100.0 * sum(1 for v in iss if v >= 2.0) / max(1, len(iss)),
                "text_changed_vs_ctrl_pct": text_changed(ctrl_rows, rows),
                "mouth_px": lip[a][stem]["mouth"],
                "face_px": lip[a][stem]["face"],
            }

    # text stability stratified by ctrl segment quality (does drift concentrate in weak segments?)
    strat = {}
    ctrl_rows = reports["mbr"]["res4k_ctrl"]
    for other in ("baseline", "res2k", "res1080"):
        orows = reports["mbr"][other]
        bands = {"IS>=3": [], "2<=IS<3": [], "IS<2": []}
        for u, r in ctrl_rows.items():
            if r["is"] is None:
                continue
            same = r["hyp"].strip() == orows[u]["hyp"].strip()
            band = "IS>=3" if r["is"] >= 3.0 else ("2<=IS<3" if r["is"] >= 2.0 else "IS<2")
            bands[band].append(same)
        strat[f"res4k_ctrl<->{other}"] = {
            b: {"n": len(v), "same_text_pct": round(100.0 * sum(v) / len(v), 1) if v else None}
            for b, v in bands.items()}
    data["text_stability_by_ctrl_is"] = strat

    # correlations (n=5 videos -- descriptive only)
    d_is = [data["per_video"]["res1080"][s]["is_mean"] - data["per_video"]["res4k_ctrl"][s]["is_mean"]
            for s in STEMS]
    mouth_ctrl = [lip["res4k_ctrl"][s]["mouth"] for s in STEMS]
    mouth_base = [lip["baseline"][s]["mouth"] for s in STEMS]
    yp = [CONTEXT_YP[s] for s in STEMS]
    is_ctrl = [data["per_video"]["res4k_ctrl"][s]["is_mean"] for s in STEMS]
    pear = sps.pearsonr(mouth_ctrl, d_is)
    spear = sps.spearmanr(mouth_ctrl, d_is)
    data["correlations"]["delta_is_ctrl_to_1080_vs_ctrl_mouth_px"] = {
        "pearson_r": float(pear[0]), "pearson_p": float(pear[1]),
        "spearman_rho": float(spear[0]), "spearman_p": float(spear[1]),
        "per_video_delta_is": dict(zip(STEMS, [round(v, 3) for v in d_is])), "n": 5}
    sp2 = sps.spearmanr(mouth_base, yp)
    pe2 = sps.pearsonr(mouth_base, yp)
    data["correlations"]["native4k_mouth_px_vs_context_yp"] = {
        "spearman_rho": float(sp2[0]), "spearman_p": float(sp2[1]),
        "pearson_r": float(pe2[0]), "pearson_p": float(pe2[1]),
        "mouth_px": dict(zip(STEMS, mouth_base)), "context_yp": CONTEXT_YP, "n": 5}
    sp3 = sps.spearmanr(mouth_ctrl, is_ctrl)
    data["correlations"]["ctrl_mouth_px_vs_ctrl_is"] = {
        "spearman_rho": float(sp3[0]), "spearman_p": float(sp3[1]), "n": 5}

    # plots
    plot_metrics_by_condition(data, lip, f"{PLOTS_DIR}/resolution_metrics_by_condition.png")
    plot_mouthpx_vs_is(data, lip, f"{PLOTS_DIR}/resolution_mouthpx_vs_delta.png")

    with open(STATS_JSON, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=1)

    # ------------------------------------------------------------------ stdout summary
    print("=" * 100)
    print("EGLA-KAFE RESOLUTION ABLATION -- 175 paired segments x 4 arms (primary: hyp_mbr display)")
    print("=" * 100)
    hdr = (f"{'arm':<28}{'n_sc':>5}{'IS':>7}{'95% CI':>16}{'WER%':>8}{'useful%':>9}{'clear%':>8}"
           f"{'NIV-Y%':>8}{'hallu%':>8}{'empty%':>8}{'wprob':>7}{'alignC':>8}")
    for basis in ("mbr", "top1"):
        print(f"\n--- {basis.upper()} ---")
        print(hdr)
        for a in ARM_ORDER:
            s = data[f"arms_{basis}"][a]
            print(f"{ARMS[a]['label']:<28}{s['n_scored']:>5}{s['is_mean']:>7.3f}"
                  f"{'[' + format(s['is_ci'][0], '.2f') + ',' + format(s['is_ci'][1], '.2f') + ']':>16}"
                  f"{s['wer_mean']:>8.1f}{s['useful_pct']:>9.1f}{s['clear_pct']:>8.1f}"
                  f"{s['niv_y_pct']:>8.1f}{s['halluc_pct']:>8.1f}{s['empty_pct']:>8.1f}"
                  f"{s['mean_word_prob']:>7.3f}{s['mean_align_conf']:>8.3f}")

    print("\n--- PAIRED TESTS (Wilcoxon signed-rank, per-segment, delta = second - first) ---")
    for k, rec in data["pairs"].items():
        m = rec["mbr"]
        print(f"{k:<24} [MBR] IS: mean_d={m['wilcoxon_is']['mean_delta']:+.3f} "
              f"med={m['wilcoxon_is']['median_delta']:+.3f} p={fmt_p(m['wilcoxon_is']['p'])} "
              f"(chg {m['wilcoxon_is']['n_changed']}/{m['wilcoxon_is']['n']}) | "
              f"WER: mean_d={m['wilcoxon_wer']['mean_delta']:+.1f} p={fmt_p(m['wilcoxon_wer']['p'])} | "
              f"text-chg {m['text_changed_pct']:.1f}% | ref-shift {rec['ref_changed_pct']:.1f}%")
        t = rec["top1"]
        print(f"{'':<24} [top1] IS: mean_d={t['wilcoxon_is']['mean_delta']:+.3f} "
              f"p={fmt_p(t['wilcoxon_is']['p'])} | WER: mean_d={t['wilcoxon_wer']['mean_delta']:+.1f} "
              f"p={fmt_p(t['wilcoxon_wer']['p'])} | text-chg {t['text_changed_pct']:.1f}%")

    print("\n--- FIXED-REF WER SENSITIVITY (MBR text vs June baseline refs, uncapped %) ---")
    print("arm means:", {a: round(v, 1) for a, v in data["fixed_ref_wer"]["arm_means"].items()},
          f"(n={data['fixed_ref_wer']['n_scoreable']})")
    for pa, pb in PAIRS:
        r = data["fixed_ref_wer"][f"{pa}->{pb}"]
        print(f"  {pa}->{pb}: mean_d={r['mean_delta']:+.1f} med={r['median_delta']:+.1f} "
              f"p={fmt_p(r['p'])} (chg {r['n_changed']}/{r['n']})")

    print("\n--- PER-VIDEO (MBR): mean IS | mouth px | text-changed vs ctrl ---")
    print(f"{'video':<10}" + "".join(f"{ARMS[a]['label']:>30}" for a in ARM_ORDER))
    for stem in STEMS:
        cells = []
        for a in ARM_ORDER:
            v = data["per_video"][a][stem]
            cells.append(f"IS {v['is_mean']:.2f} @{v['mouth_px']:>3}px chg{v['text_changed_vs_ctrl_pct']:>3.0f}%")
        print(f"{stem:<10}" + "".join(f"{c:>30}" for c in cells))

    print("\n--- TEXT STABILITY vs res4k_ctrl, stratified by ctrl segment IS (MBR text) ---")
    for pair, bands in data["text_stability_by_ctrl_is"].items():
        cells = ", ".join(f"{b}: {v['same_text_pct']}% same (n={v['n']})" for b, v in bands.items())
        print(f"  {pair}: {cells}")

    print("\n--- CORRELATIONS (n=5 videos, descriptive) ---")
    c = data["correlations"]["delta_is_ctrl_to_1080_vs_ctrl_mouth_px"]
    print(f"dIS(ctrl->1080) vs ctrl mouth px: pearson r={c['pearson_r']:+.3f} (p={c['pearson_p']:.3f}), "
          f"spearman rho={c['spearman_rho']:+.3f}; per-video dIS: {c['per_video_delta_is']}")
    c = data["correlations"]["native4k_mouth_px_vs_context_yp"]
    print(f"native-4K mouth px vs context Y+P: spearman rho={c['spearman_rho']:+.3f} (p={c['spearman_p']:.3f}), "
          f"pearson r={c['pearson_r']:+.3f} (p={c['pearson_p']:.3f})")
    c = data["correlations"]["ctrl_mouth_px_vs_ctrl_is"]
    print(f"ctrl mouth px vs ctrl IS: spearman rho={c['spearman_rho']:+.3f} (p={c['spearman_p']:.3f})")
    print(f"\nwrote: {STATS_JSON}")
    print(f"wrote: {PLOTS_DIR}/resolution_metrics_by_condition.png")
    print(f"wrote: {PLOTS_DIR}/resolution_mouthpx_vs_delta.png")


if __name__ == "__main__":
    main()
