#!/usr/bin/env python3
"""
Generate segment_timing.json from segment_metadata.json and manifest.

This script reads:
- segment_metadata.json (from overlapping preprocessing)
- train.tsv (manifest generated by make_simple_manifest.py)

And produces:
- segment_timing.json (timing info + overlap detection for merge module)

Usage:
    python generate_segment_timing.py \
        --manifest-tsv preprocessed_flat_seg4/433h_data/train.tsv \
        --segment-metadata preprocessed_flat_seg4/segment_metadata.json \
        --output-json preprocessed_flat_seg4/433h_data/segment_timing.json
"""

import argparse
import json
import re
from pathlib import Path
from typing import Dict, List, Optional


def parse_segment_filename(filename: str) -> Optional[Dict]:
    """Extract timing from segment filename with frame ranges."""
    # Remove file extension if present (e.g., .mp4, .mkv)
    # Only remove extension if it looks like a video file extension
    if filename.endswith(('.mp4', '.mkv', '.avi', '.mov', '.webm')):
        basename = Path(filename).stem
    else:
        # Already a basename/stem, use as-is
        basename = filename

    # Try pattern 1: {id}__{hash}_{idx}_{start}_{end}
    pattern1 = r'^(.+?)__([a-f0-9]{8})_(\d{2})_(\d{6})_(\d{6})$'
    match = re.match(pattern1, basename)
    if match:
        return {
            'video_id': match.group(1),
            'hash': match.group(2),
            'seg_idx': int(match.group(3)),
            'start_frame': int(match.group(4)),
            'end_frame': int(match.group(5)),
            'full_id': f"{match.group(1)}__{match.group(2)}"
        }

    # Try pattern 2: {video_name}_{idx}_{start}_{end} (no hash)
    pattern2 = r'^(.+?)_(\d{2})_(\d{6})_(\d{6})$'
    match = re.match(pattern2, basename)
    if match:
        video_base = match.group(1)
        return {
            'video_id': video_base,
            'hash': None,
            'seg_idx': int(match.group(2)),
            'start_frame': int(match.group(3)),
            'end_frame': int(match.group(4)),
            'full_id': video_base  # No hash, so full_id is just the video base name
        }

    # Fallback pattern 3: {id}__{hash} (old format without frame info)
    pattern3 = r'^(.+?)__([a-f0-9]{8})$'
    match = re.match(pattern3, basename)
    if match:
        return {
            'video_id': match.group(1),
            'hash': match.group(2),
            'seg_idx': 0,
            'start_frame': None,
            'end_frame': None,
            'full_id': basename
        }

    return None


def generate_timing_metadata(manifest_tsv: str, segment_metadata_json: str, output_json: str):
    """Generate segment_timing.json for merge module."""
    
    # Load segment metadata
    try:
        with open(segment_metadata_json, 'r') as f:
            segment_metadata = json.load(f)
        print(f"✓ Loaded segment metadata: {len(segment_metadata)} videos")
    except FileNotFoundError:
        print(f"ERROR: {segment_metadata_json} not found")
        return
    
    # Read manifest TSV
    try:
        with open(manifest_tsv, 'r') as f:
            lines = f.read().strip().splitlines()
        print(f"✓ Loaded manifest: {len(lines)} lines")
    except FileNotFoundError:
        print(f"ERROR: {manifest_tsv} not found")
        return
    
    # Parse TSV entries
    manifest_entries = []
    for line in lines:
        if not line.strip() or line.startswith('#'):  # Skip empty lines and comments
            continue
        parts = line.split('\t')
        if len(parts) < 4:
            continue
        utt_id = Path(parts[1]).stem
        manifest_entries.append({'utt_id': utt_id, 'nframes': int(parts[3])})
    
    print(f"  Parsed {len(manifest_entries)} segments")
    
    # Generate timing metadata
    timing_metadata = {}
    segment_groups = {}
    
    for entry in manifest_entries:
        utt_id = entry['utt_id']
        parsed = parse_segment_filename(utt_id)
        if not parsed:
            continue
        
        full_id = parsed['full_id']
        seg_idx = parsed['seg_idx']
        
        # Get timing from metadata
        if full_id in segment_metadata:
            meta = segment_metadata[full_id]
            if seg_idx < len(meta['segments']):
                seg_info = meta['segments'][seg_idx]
                timing_metadata[utt_id] = {
                    'video_id': parsed['video_id'],
                    'full_id': full_id,
                    'segment_index': seg_idx,
                    'start_frame': seg_info['start_frame'],
                    'end_frame': seg_info['end_frame'],
                    'start_sec': seg_info['start_sec'],
                    'end_sec': seg_info['end_sec'],
                    'duration': seg_info['duration'],
                    'overlaps_with': []
                }
                if full_id not in segment_groups:
                    segment_groups[full_id] = []
                segment_groups[full_id].append(utt_id)
    
    # Detect overlaps
    overlap_count = 0
    for full_id, utt_ids in segment_groups.items():
        utt_ids_sorted = sorted(utt_ids, key=lambda u: timing_metadata[u]['segment_index'])
        for i in range(len(utt_ids_sorted) - 1):
            info1 = timing_metadata[utt_ids_sorted[i]]
            info2 = timing_metadata[utt_ids_sorted[i + 1]]
            if info1['end_frame'] > info2['start_frame']:
                info1['overlaps_with'].append(info2['segment_index'])
                info2['overlaps_with'].append(info1['segment_index'])
                overlap_count += 1
    
    # Write output
    Path(output_json).parent.mkdir(parents=True, exist_ok=True)
    with open(output_json, 'w') as f:
        json.dump(timing_metadata, f, indent=2)
    
    print(f"\n✓ Segment timing written to: {output_json}")
    print(f"  Segments: {len(timing_metadata)}, Videos: {len(segment_groups)}, Overlaps: {overlap_count}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest-tsv", required=True)
    parser.add_argument("--segment-metadata", required=True)
    parser.add_argument("--output-json", required=True)
    args = parser.parse_args()
    generate_timing_metadata(args.manifest_tsv, args.segment_metadata, args.output_json)
